### ISSUE TITLE
mattermost channel

### ISSUE THREAD

**Issue by psteinb** [VLL-HD/FrEIA-community#1]
invite link for use with github accounts or Helmholtz AAI

https://mattermost.hzdr.de/signup_user_complete/?id=n87gmq1877rzfqnmdr1isyc5or

**Comment by psteinb** [comment]
Please let me know if there are problems with this link.

**Comment by ardizzone** [comment]
The link works!
Then, there is a `freia-hackathon` channel, which is probably the one we should use. ;)

**Comment by psteinb** [comment]
Exactly! See you there.
